// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kicdurgmaggwvtpngrxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpY2R1cmdtYWdnd3Z0cG5ncnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzQ5OTksImV4cCI6MjA3MDkxMDk5OX0.zv6Zl1KkY9bZnDjBd2opBd6iIxU3CrmIx6oR5_KP9aY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});